# Generated by Django 5.2.9 on 2025-12-04 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_of_following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
